Tag.find_or_create_by(name: "affectionate")
Tag.find_or_create_by(name: "low shedding")
Tag.find_or_create_by(name: "playful")
Tag.find_or_create_by(name: "intelligent")
Tag.find_or_create_by(name: "has no tail")
Tag.find_or_create_by(name: "friendly")
Tag.find_or_create_by(name: "pet friendly")
Tag.find_or_create_by(name: "knows kung fu")
Tag.find_or_create_by(name: "climbs trees")
